import { CardData } from "@/types/types";
import { Dict } from "@/types/dict";


export const initialDict: Dict = {
    services: {
    خدمات_تابلو_برق: "Electrical Panel Services",
    خدمات_برد_های_الکترونیکی: "Electronic Board Services",
    خدمات_سیم_پیچی_و_تعمیرات_دستگاه_های_صنعتی: "Coil Winding and Industrial Machine Repair Services",
    خدمات_لوازم_برقی_خانگی_کوچک: "Small Household Appliance Services",
    خدمات_ابزار_های_برقی_صنعتی: "Industrial Power Tools Services",
    تابلو_برق_فشار_ضعیف: "Low Voltage Panel",
    تابلو_کنترل_صنعتی: "Industrial Control Panel",
    تابلو_اتوماسیون: "Automation Panel",
    تابلو_توزیع: "Distribution Panel",
    برد_های_کنترلی_صنعتی: "Industrial Control Boards",
    برد_های_قدرت_و_درایو: "Power and Drive Boards",
    برد_های_لوازم_خانگی: "Household Appliance Boards",
    برد_های_اتوماسیون_و_پی_ال_سی: "Automation and PLC Boards",
    الکتروموتور_های_جریان_مستقیم_و_متناوب: "AC and DC Electric Motors",
    الکتروموتور_های_تخصصی_خط_تولید: "Production Line Special Electric Motors",
    ماشین_الات_صنعتی_کارگاهی: "Workshop Industrial Machinery",
    تجهیزات_انتقال_و_جابجایی_مواد: "Material Handling Equipment",
    تجهیزات_سرمایش_و_تهویه_و_سیالات: "Cooling, Ventilation and Fluid Equipment",
    ژنراتور_ها_و_ترانس_ها: "Generators and Transformers",
    لوازم_آشپزخانه: "Kitchen Appliances",
    لوازم_نظافت: "Cleaning Appliances",
    لوازم_حرارتی_و_گرمایشی: "Heating and Thermal Appliances",
    لوازم_شخصی_و_بهداشتی: "Personal Care Appliances",
    لوازم_برقی_عمومی: "General Electric Appliances",
    ابزار_های_برش_و_سایش: "Cutting and Grinding Tools",
    ابزار_های_سوراخکاری_و_بازو_بستن: "Drilling and Fastening Tools",
    ابزار_های_نظافت_و_شستشوی_صنعتی: "Industrial Cleaning and Washing Tools",
    ابزار_های_حرارتی: "Heating Tools",
    ابزار_های_فشرده_سازی_و_هوا: "Compression and Air Tools",
    ابزار_های_کشاورزی: "Agricultural Tools",
    ابزار_های_اندازه_گیری: "Measuring Tools",
    برد_های_لوازم_برقی_صنعتی: "Industrial Appliance Boards",
    برد_های_درایو: "Drive Boards",
    برد_های_لوازم_برقی_خانگی: "Home Appliance Boards",
    برد_های_پی_ال_سی: "PLC Boards",
    الکتروموتورهای_جریان_متناوب: "AC Electric Motors",
    الکتروموتورهای_جریان_مستقیم: "DC Electric Motors",
    ماشین_های_الکتریکی_جریان_مستقیم: "DC Electric Machines",
    الکتروموتورهای_اکسترودر: "Extruder Motors",
    الکتروموتورهای_آجر_و_بلوک_زنی: "Brick and Block Making Motors",
    الکتروموتورهای_پرس_هیدرولیک_صنعتی: "Industrial Hydraulic Press Motors",
    الکتروموتورهای_بالابر: "Elevator Motors",
    الکتروموتورهای_دستگاه_بالانس: "Balancing Machine Motors",
    دریل_ستونی: "Column Drill",
    دریل_رادیال: "Radial Drill",
    دستگاه_تراش: "Lathe Machine",
    دستگاه_پانچ_لوله: "Pipe Punching Machine",
    دستگاه_آسیاب: "Milling Machine",
    دستگاه_هابینگ: "Hobbing Machine",
    گیوتین: "Guillotine Shear",
    ماشین_فرز: "Milling Machine",
    مینی_تراش: "Mini Lathe",
    میکسر: "Mixer",
    نوار_نقاله: "Conveyor Belt",
    الکتروموتورهای_پمپ_آب: "Water Pump Motors",
    رادیاتور_صنعتی: "Industrial Radiator",
    کولر_آبی: "Evaporative Cooler",
    هواکش_صنعتی: "Industrial Fan",
    ترانس_های_تکفاز_و_سه_فاز: "Single-phase and Three-phase Transformers",
    ژنراتور_دیزلی: "Diesel Generator",
    کمپرسور_دینامی: "Dynamic Compressor",
    آسیاب_قهوه_خانگی: "Home Coffee Grinder",
    ابمیوه_گیری: "Juicer",
    اجاق_برقی: "Electric Stove",
    اسپرسو_ساز_خانگی: "Home Espresso Machine",
    اسنک_پز: "Snack Maker",
    بخارپز: "Steamer",
    توستر: "Toaster",
    چای_ساز: "Tea Maker",
    چرخ_گوشت: "Meat Grinder",
    رنده_برقی: "Electric Grater",
    سرخ_کن: "Deep Fryer",
    سماور_برقی: "Electric Samovar",
    گوشتکوب_برقی: "Electric Meat Tenderizer",
    مایکروفر: "Microwave Oven",
    مایکروویو: "Microwave",
    هاون_برقی: "Electric Mortar",
    همزن_برقی: "Electric Mixer",
    اپیلیدی_موکن: "Epilator",
    بخارشوی_خانگی: "Home Steam Cleaner",
    جاروبرقی: "Vacuum Cleaner",
    کارواش_خانگی: "Home Pressure Washer",
    مینی_واش: "Mini Washer",
    اتو_بخار: "Steam Iron",
    اتو_پرسی: "Pressing Iron",
    اتو_خانگی: "Home Iron",
    بخاری_برقی: "Electric Heater",
    پنکه: "Fan",
    سشوار: "Hair Dryer",
    اتو_صورت: "Facial Steamer",
    بابیلیس: "Hair Styler (Babyliss)",
    بند_انداز: "Hair Straightener",
    ریش_تراش: "Electric Shaver",
    موزر: "Massager",
    بخور: "Humidifier",
    آسیاب_قهوه_صنعتی: "Industrial Coffee Grinder",
    اره_میزی: "Table Saw",
    اره_عمودبر: "Vertical Saw",
    اره_برقی: "Electric Saw",
    اره_نواری: "Band Saw",
    اور_فرز_نجاری: "Woodworking Router",
    شیارزن: "Grooving Machine",
    سنگ_فرز_بزرگ: "Large Milling Machine",
    فرز_مینیاتوری: "Micro Grinder",
    فرز_انگشتی: "Die Grinder",
    فارسی_بر: "Miter Saw",
    قیچی_شارژی: "Cordless Shears",
    مینی_فرز: "Mini Milling Machine",
    لوله_بر: "Pipe Cutter",
    لاک_تراش: "Lacquer Scraper",
    بکس_شارژی: "Cordless Impact Wrench",
    پیچ_گوشتی_برقی: "Electric Screwdriver",
    پرس_کابلشو_برقی: "Electric Cable Lug Press",
    چکش_تخریب: "Demolition Hammer",
    دریل: "Drill",
    حدیده_برقی: "Electric Threading Machine",
    دریل_مگنتی: "Magnetic Drill",
    دریل_شارژی: "Cordless Drill",
    دریل_چکشی: "Hammer Drill",
    دستگاه_پولیش: "Polishing Machine",
    دریل_همزن: "Mixer Drill",
    ژنراتور_کوچک: "Small Generator",
    ویبراتور: "Vibrator",
    هیلتی: "Rotary Hammer (Hilti)",
    بخارشوی_صنعتی: "Industrial Steam Cleaner",
    جاروبرقی_صنعتی: "Industrial Vacuum Cleaner",
    کارواش_شارژی: "Cordless Pressure Washer",
    کارواش_دینامی: "Dynamic Pressure Washer",
    کارواش_صنعتی: "Industrial Pressure Washer",
    اتو_صنعتی: "Industrial Iron",
    اتو_لوله_کشی: "Pipe Iron",
    اسپرسوساز_صنعتی: "Industrial Espresso Machine",
    سشوار_صنعتی: "Industrial Hair Dryer",
    دستگاه_نقطه_جوش: "Spot Welding Machine",
    بلوور: "Blower",
    پمپ_باد_شارژی: "Cordless Air Pump",
    دستگاه_آرماتورپیچ: "Rebar Tying Machine",
    کمپرسور_باد_کوچک: "Small Air Compressor",
    کمپرسور: "Compressor",
    چرخ_گوشت_صنعتی: "Industrial Meat Grinder",
    چمن_زن_برقی: "Electric Lawn Mower",
    سمپاش_برقی: "Electric Sprayer"
    },

    logo: "Maher Services",
    logoPt1: "Soleimani",
    logoPt2: "Rice",
    search: "Search",
    in: "in",
    categories: "Categories",

  providingSpecializedCoilWindingAndRepairServicesForAllTypesOfElectricMotorsWithYearsOfExperienceAndQualityGuarantee: "Providing specialized coil winding and repair services for all types of electric motors with years of experience and quality guarantee",
  ourServices: "Our Services",
  contactUs: "Contact Us",
  industrialDistrict: "Dolat Abad Industrial District",
  workingHoursDays: "Saturday to Thursday",
  workingHoursTime: "8 AM to 8 PM",
  allRightsReserved: "© 2026 Sim Pechi Maher. All rights reserved.",
  designedAndDevelopedByWebitur: "Designed and developed by Webitur (09301047368 Poursoleimani)",
  withMoreThanTenValidTechnicalCertificates: "With more than ten valid technical certificates",
  andYearsOfExperienceAtYourService: "And years of experience at your service",
      request: "request",
      requestService: "Request Service",
    pleaseContactTheNumberBellow: "Please Contact The Number Bellow",
    close: "close"

};