import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Arabic, Vazirmatn } from "next/font/google";
import "./globals.css";
import ClientLayoutWrapper from "./ClientLayoutWrapper";
import { SettingsInitializer } from "@/components/settings-initializer";
import { MessagesProvider } from "@/contexts/MessagesContext";
import { MessagesContainer } from "@/components/ui/MessagesContainer";
import { DataInitializer } from "@/components/data-initializer";
import { CookiesProvider } from "next-client-cookies/server";

const vazirmatn = Vazirmatn({
  subsets: ['arabic', 'latin'],
  display: 'swap',
  variable: '--font-vazirmatn'
})

const notoSansArabic = Noto_Sans_Arabic({
  subsets: ['arabic'],
  display: 'swap',
  variable: '--font-noto-arabic'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {

  const { lang } = await params
  return (
    <html lang="en" className={`scrollbar-hide ${vazirmatn.variable} select-none`}>
      <body
        className={`${vazirmatn.className} antialiased`}
      >
        <CookiesProvider>
            <DataInitializer lang={lang}>
              <SettingsInitializer lang={lang}>
                <ClientLayoutWrapper lang={lang}>
                  <MessagesProvider>
                    {children}
                    <MessagesContainer position="top-center" />
                  </MessagesProvider>
                </ClientLayoutWrapper>
              </SettingsInitializer>
            </DataInitializer>
        </CookiesProvider>
      </body>
    </html>
  );
}
